/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tWxhPy4ond6
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function WelcomeHero() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container flex flex-col items-center justify-center space-y-4 px-4 text-center md:px-6">
        <div className="space-y-3">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Coming Soon</h1>
          <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            We're working on something special. Sign up to be the first to know when it launches.
          </p>
        </div>
        <form className="flex mx-auto max-w-sm">
          <Input placeholder="Enter your email" required type="email" />
          <Button type="submit">Sign Up</Button>
        </form>
      </div>
    </section>
  )
}
